version: '3'

networks:
    app-tier:
      driver: bridge

services:
    postgresql-master:
      image: 'bitnami/postgresql'
      container_name: postgres-master
      networks:
        - app-tier
      ports:
        - '32780:5432'
      volumes:
        - 'postgresql_master_data:/bitnami/postgresql'
      environment:
        - POSTGRESQL_REPLICATION_MODE=master
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_password
        - POSTGRESQL_USERNAME=postgres
        - POSTGRESQL_PASSWORD=postgres
        - POSTGRESQL_DATABASE=shorten_url
    postgresql-servant:
      image: 'bitnami/postgresql'
      networks:
        - app-tier
      ports:
        - '32781-32783:5432'
      depends_on:
        - postgresql-master
      environment:
        - POSTGRESQL_REPLICATION_MODE=slave
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_password
        - POSTGRESQL_MASTER_HOST=postgresql-master
        - POSTGRESQL_PASSWORD=postgres
        - POSTGRESQL_MASTER_PORT_NUMBER=5432
  
volumes:
  postgresql_master_data:
    driver: local

# docker-compose up -d --scale postgresql-master=1 --scale postgresql-servant=3